### ISSUE TITLE
"Error rendering embedded code  Invalid PDF"

### ISSUE THREAD

**Issue by 0x0a53** [heckerpowered/Jvav#38]
**Describe the bug**

**To Reproduce**
1. Go to '[Jvav](https://github.com/heckerpowered/Jvav)'
2. Click on 'docs/draft/'
3. Scroll down to 'Jvav 24.pdf'

**Expected behavior**
You should see the PDF content.
But it show message "Unable to render code block".

**Screenshots**
No screenshots.

**Comment by heckerpowered** [comment]
I can render it correctly, have you considered it's network issue?

**Comment by 0x0a53** [comment]
I can only see the content of the "*. typ" file.

**Comment by heckerpowered** [comment]
> I can only see the content of the "*. typ" file.

Did you access this file via github.com?(not a mirror website), did you use the proxy? Have you tried to download it and check it?

**Comment by 0x0a53** [comment]
Show:"Error rendering embedded code

Invalid PDF"

**Comment by 0x0a53** [comment]
I download it, and it can work.

**Comment by heckerpowered** [comment]
> Show:"Error rendering embedded code
> 
> Invalid PDF"

It seems a network issue, do not use mirror website, use the proxy and try again

**Comment by 0x0a53** [comment]
I don't have proxy, but I am not currently using a mirror.

**Comment by 0x0a53** [comment]
<img width="960" alt="image" src="https://github.com/user-attachments/assets/9cb5c55d-d22c-4102-8ab9-07bdb819d891">

**Comment by heckerpowered** [comment]
Based on the information you provided, it looks like a network issue and cannot be reproduced. The issue will be closed if there’s no objections.

**Comment by 0x0a53** [comment]
OK.I can download it and read it.
